{
  "formatVersion": "1.1",
  "component": {
    "group": "com.algorix",
    "module": "ads-sdk",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ads-sdk-1.0.1.aar",
          "url": "ads-sdk-1.0.1.aar",
          "size": 514681,
          "sha512": "0fe7aa3f1bed9a87ab719da2c997f6c268d39dcf3c15ca4c8487c077839ae064112a6301aeea88f64f8e812bdd589a139d35c9502549d3b96093351783dff25a",
          "sha256": "a2d7678e9e8322f0e97643189a8ecd9dbaa97b68d697a9860779e7a9bbeecef0",
          "sha1": "ee8ca6045f99fd216742b96bd1222e81b18a3b0f",
          "md5": "abb2e1f186d9faf59ae13c55912d5b2c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "ads-sdk-1.0.1.aar",
          "url": "ads-sdk-1.0.1.aar",
          "size": 514681,
          "sha512": "0fe7aa3f1bed9a87ab719da2c997f6c268d39dcf3c15ca4c8487c077839ae064112a6301aeea88f64f8e812bdd589a139d35c9502549d3b96093351783dff25a",
          "sha256": "a2d7678e9e8322f0e97643189a8ecd9dbaa97b68d697a9860779e7a9bbeecef0",
          "sha1": "ee8ca6045f99fd216742b96bd1222e81b18a3b0f",
          "md5": "abb2e1f186d9faf59ae13c55912d5b2c"
        }
      ]
    }
  ]
}
